### ISSUE TITLE
Phantom blank lines are added at the end of the code blocks

### ISSUE THREAD

**Issue by jscarle** [Automattic/syntaxhighlighter#274]
If you take a look at this [post](https://blog.jscarle.dev/2024/02/14/the-operation-result-pattern-will-save-your-net-application-from-death-by-a-thousand-exceptions/) on my blog, you'll see various instances of extra blank lines at the end of various code blocks. There's not from my input. I have deleted the code blocks, went into Notepad++ with all symbols shown, verified that I had no extra blank lines, and recreated the code block and those lines still appear.

The worse instance is the benchmark at the end which even adds not 1, but 2 blank lines.

![image](https://github.com/Automattic/syntaxhighlighter/assets/29762210/06e996e7-402f-44ed-bbbc-333aeb6ed620)

![image](https://github.com/Automattic/syntaxhighlighter/assets/29762210/3343f65a-726c-4027-992b-35e1e596d83e)

Running version 3.7.0 of SyntaxHighlighter Evolved.

My settings:
![image](https://github.com/Automattic/syntaxhighlighter/assets/29762210/4135fb2f-ecb4-4dc5-bc85-e879b77b7cdf)

The override CSS class:
```css
.syntaxhighlighter.override a,
.syntaxhighlighter.override div,
.syntaxhighlighter.override code,
.syntaxhighlighter.override table,
.syntaxhighlighter.override table td,
.syntaxhighlighter.override table tr,
.syntaxhighlighter.override table tbody,
.syntaxhighlighter.override table thead,
.syntaxhighlighter.override table caption,
.syntaxhighlighter.override textarea {
  font-size: 0.94em !important;
}
```

Running WordPress 6.4.3 with the [Twenty Nineteen](https://blog.jscarle.dev/wp-admin/themes.php) theme.

**Comment by jscarle** [comment]
I just realised that it's not adding blank lines, its my CSS that doesn't work properly. The line-height gets computed differently for the gutter vs the code.

**Comment by jscarle** [comment]
I'm going to add this to the issue in case anyone ever comes across this one day.

The fix was to add `.syntaxhighlighter.override` to the list of classes.

Thus, this:
```css
.syntaxhighlighter.override,
.syntaxhighlighter.override a,
.syntaxhighlighter.override div,
.syntaxhighlighter.override code,
.syntaxhighlighter.override table,
.syntaxhighlighter.override table td,
.syntaxhighlighter.override table tr,
.syntaxhighlighter.override table tbody,
.syntaxhighlighter.override table thead,
.syntaxhighlighter.override table caption,
.syntaxhighlighter.override textarea {
  font-size: 0.67rem !important;
  line-height: 0.85rem !important;
}
```
Works consistently on both the gutter and the code.
