### ISSUE TITLE
Removing the lines on the right hand side border

### ISSUE THREAD

**Issue by alex-harvey-z3q** [Automattic/syntaxhighlighter#55]
Hi there, how can I get rid of these lines on the right hand side, it seems to appear at about 70 characters?  If you see [here](http://razorconsulting.com.au/building-a-highly-available-elk-solution-with-puppet-part-ii-elasticsearch-backend.html) it doesn't look good at all.  Thanks for the awesome plugin by the way.

**Comment by Viper007Bond** [comment]
It's being added by your theme. Notice the same line to the right of the rest of your post.

I used the inspector tools in my browser and determined that it's this CSS rule from your theme that's causing it:

``` css
.et_right_sidebar #main-content .container:before {
    right: 20.875% !important;
}
```

SyntaxHighlighter has a `div` within it with the class `container`, so the rule is getting applied there too.

Adding this CSS rule to the bottom of your theme's stylesheet seems to fix it:

``` css
.et_right_sidebar #main-content .syntaxhighlighter .container:before {
    right: auto !important;
}
```
